---
- name: Managment KVM
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Environment {{ action }}"
      community.libvirt.virt:
        name: "{{ item }}"
        state: "{{ action }}"
      loop: "{{ vm_name }}"
      when:
        - vm_name is defined
        - action is defined

    - name: Beelink Shutdodwn
      community.general.shutdown:
      when: beelink == "SI"
