---
- name: Managment KVM
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: "Environment {{ action }}"
      community.libvirt.virt:
        name: "{{ item }}"
        state: "{{ action }}"
      loop: "{{ vm_name }}"
